# Generated by Django 6.0 on 2026-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('explanation', models.TextField()),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='user',
        ),
        migrations.DeleteModel(
            name='PracticeQuestion',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
